// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaD6vWslJXrjUa11j2e-vLdD1FyKjz0l0',
    appId: '1:1088786926370:web:c7930fc2c6fbf5b915b37b',
    messagingSenderId: '1088786926370',
    projectId: 'todoapp-dc180',
    authDomain: 'todoapp-dc180.firebaseapp.com',
    storageBucket: 'todoapp-dc180.appspot.com',
    measurementId: 'G-Y147QHBEHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfB-Svefe0_ee2p54AteV5lDA3yB13F5U',
    appId: '1:1088786926370:android:2c54dd9c08a1cd5115b37b',
    messagingSenderId: '1088786926370',
    projectId: 'todoapp-dc180',
    storageBucket: 'todoapp-dc180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHejB-oABaED3NZNBaJmZA_2kYEG-SLc4',
    appId: '1:1088786926370:ios:8d4c7643dc5051f515b37b',
    messagingSenderId: '1088786926370',
    projectId: 'todoapp-dc180',
    storageBucket: 'todoapp-dc180.appspot.com',
    iosBundleId: 'com.example.pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHejB-oABaED3NZNBaJmZA_2kYEG-SLc4',
    appId: '1:1088786926370:ios:1ed7b42d49f2f51c15b37b',
    messagingSenderId: '1088786926370',
    projectId: 'todoapp-dc180',
    storageBucket: 'todoapp-dc180.appspot.com',
    iosBundleId: 'com.example.pro.RunnerTests',
  );
}
